# Generated by Django 3.0.4 on 2020-04-06 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, height_field=427, upload_to='', width_field=640),
            preserve_default=False,
        ),
    ]
