# Generated by Django 3.0.4 on 2020-04-06 15:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200406_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imgpic_90x90',
            field=imagekit.models.fields.ProcessedImageField(default='fjc.jpg', upload_to='DF_goods/Image/%Y/%m'),
            preserve_default=False,
        ),
    ]
