# Generated by Django 3.0.4 on 2020-04-11 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200406_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Introduction',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
