# Generated by Django 3.0.4 on 2020-04-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_blog_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Introduction',
            new_name='introduction',
        ),
    ]
