# Generated by Django 3.0.4 on 2020-04-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200411_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='introduction',
            field=models.CharField(max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=254, unique=True, verbose_name='标题'),
        ),
    ]
