# Generated by Django 3.0.4 on 2020-04-11 09:05

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200411_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imgpic_640x427',
            field=imagekit.models.fields.ProcessedImageField(upload_to='DF_goods/Image/%Y/%m', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='introduction',
            field=models.CharField(max_length=60, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='标题'),
        ),
    ]
